AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  serverlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: alexa-sandbox
      CodeUri: src/handlers
      Handler: index.handler
      Runtime: nodejs6.10
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
      Environment:
        Variables:
          TZ: 'Asia/Tokyo'
