AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Rds:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: 'xblood-rds-mysql'
      DBName: 'xblood_rds'
      Engine: MySQL
      EngineVersion: 5.6
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      AvailabilityZone: ap-northeast-1a
      MasterUsername: 'root'
      MasterUserPassword: 'password'
      Port: 3306
      VPCSecurityGroups:
        - !Ref 'RdsSecurityGroup'
      StorageEncrypted: false
      DBParameterGroupName: !Ref 'RdsDBParameterGroup'
      DBSubnetGroupName: !Ref 'RdsSubnetGroup'
  
  RdsDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: 'for xblood-rds-mysql'
      Family: 'mysql5.6'
      Parameters:
        time_zone: 'Asia/Tokyo'
  
  RdsSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: 'for xblood-rds-mysql'
      DBSubnetGroupName: 'xblood-rds-mysql'
      SubnetIds:
        - Fn::ImportValue: 'PrivateSubnet0'
        - Fn::ImportValue: 'PrivateSubnet1'

  RdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 'rds-mysql-sg'
      GroupDescription: 'for xblood-rds-mysql'
      Tags:
      -
        Key: 'Name'
        Value: 'rds-mysql-sg'
      # VPC
      VpcId:
        Fn::ImportValue: 'VpcId'

Outputs:
  RdsIdentifier:
    Value: !Ref Rds
    Export:
      Name: RdsIdentifier
  RdsSecurityGroupId:
    Value: !Ref RdsSecurityGroup
    Export:
      Name: RdsSecurityGroupId