# aws cloudformation validate-template --template-body file://~/tech/xblood-aws-handson/cfn/rds.yml --profile 
# aws cloudformation create-stack --stack-name rds --template-body file://~/tech/xblood-aws-handson/cfn/rds.yml --parameters ParameterKey=XbdbUser,ParameterValue=${XB_AWS_HANDSON_XBDB_USER} ParameterKey=XbdbPassword,ParameterValue=${XB_AWS_HANDSON_XBDB_PASSWORD} --profile 
# aws cloudformation create-change-set --stack-name rds --change-set-name rds-change-set --template-body file://~/tech/xblood-aws-handson/cfn/rds.yml --parameters ParameterKey=XbdbUser,ParameterValue=${XB_AWS_HANDSON_XBDB_USER} ParameterKey=XbdbPassword,ParameterValue=${XB_AWS_HANDSON_XBDB_PASSWORD} --profile 
# aws cloudformation delete-stack --stack-name rds --profile 

AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  XbdbUser:
    Type: String
  XbdbPassword:
    Type: String

Resources:
  Rds:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: 'xblood-rds-mysql'
      DBName: 'xbdb'
      Engine: MySQL
      EngineVersion: 5.6
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      AvailabilityZone: ap-northeast-1a
      MasterUsername:
        Ref: XbdbUser
      MasterUserPassword:
        Ref: XbdbPassword
      Port: 3306
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !Ref 'RdsSecurityGroup'
      StorageEncrypted: false
      DBParameterGroupName: !Ref 'RdsDBParameterGroup'
      DBSubnetGroupName: !Ref 'RdsSubnetGroup'

  RdsDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: 'for xblood-rds-mysql'
      Family: 'mysql5.6'
      Parameters:
        time_zone: 'Asia/Tokyo'

  RdsSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: 'for xblood-rds-mysql'
      DBSubnetGroupName: 'xblood-rds-mysql'
      SubnetIds:
        - Fn::ImportValue: 'PublicSubnet0'
        - Fn::ImportValue: 'PublicSubnet1'

  RdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 'rds-mysql-sg'
      GroupDescription: 'for xblood-rds-mysql'
      Tags:
        -
          Key: 'Name'
          Value: 'rds-mysql-sg'
      VpcId:
        Fn::ImportValue: 'VpcId'

Outputs:
  RdsIdentifier:
    Value: !Ref Rds
    Export:
      Name: RdsIdentifier
  RdsSecurityGroupId:
    Value: !Ref RdsSecurityGroup
    Export:
      Name: RdsSecurityGroupId