AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.192.0/16

  Ig:
    Type: AWS::EC2::InternetGateway

  GWAttachment0:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref Ig
      VpcId: !Ref Vpc

  PublicSubnet0:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 192.168.192.0/24
      MapPublicIpOnLaunch: 'true'
      VpcId: !Ref Vpc

  PrivateSubnet0:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 192.168.193.0/24
      VpcId: !Ref Vpc

Outputs:
  VpcId:
    Value: !Ref Vpc
    Export:
      Name: 'VpcId'
  PublicSubnet0Id:
    Value: !Ref PublicSubnet0
    Export:
      Name: 'PublicSubnet0'
  PrivateSubnet0Id:
    Value: !Ref PrivateSubnet0
    Export:
      Name: 'PrivateSubnet0'
