AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  alexaBookingMeetingRoomFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: alexa-booking-meeting-room
      CodeUri: src/handlers
      Handler: index.handler
      Runtime: nodejs6.10
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
      Environment:
        Variables:
          TZ: 'Asia/Tokyo'
